const dummyPost = {
  id: 'mgr3nl',
  type: 'meme',
  title: 'Why',
  postLink: 'https://redd.it/mgr3nl',
  image: 'https://i.redd.it/hwxuptbjm8q61.jpg',
  thumbnail:
    'https://b.thumbs.redditmedia.com/c-GJZ4gWoG46RGoSsdMgR0s5iF8DSjUTJGGE2KNa9bI.jpg',
  subreddit: 'BikiniBottomTwitter',
  NSFW: false,
  spoiler: false,
  createdUtc: 1617141538,
  upvotes: 13,
  upvoteRatio: 1,
};

const dummyPack = [
  {
    id: 'mg9m07',
    type: 'meme',
    title: 'Waiting Room Starter Pack',
    postLink: 'https://redd.it/mg9m07',
    image: 'https://i.redd.it/iwvxxmp404q61.jpg',
    thumbnail:
      'https://b.thumbs.redditmedia.com/VFVDWzipg-pJRkMH8z_Tx77xyw6lDeBc8tneDsDrTyg.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617085573,
    upvotes: 34576,
    upvoteRatio: 0.95,
  },
  {
    id: 'mgqep7',
    type: 'meme',
    title: 'Early Millennial (born 1981-1986) kid Culture Starterpack',
    postLink: 'https://redd.it/mgqep7',
    image: 'https://i.redd.it/5hqiwy55g8q61.png',
    thumbnail:
      'https://b.thumbs.redditmedia.com/8uozEmz3qsTTP3Jo_0Ub1-kk5NZar-2gUVVnia8DNSU.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617139465,
    upvotes: 14,
    upvoteRatio: 0.89,
  },
  {
    id: 'mge0xi',
    type: 'meme',
    title: 'Saying you enjoy EDM on Reddit Starter Pack',
    postLink: 'https://redd.it/mge0xi',
    image: 'https://i.redd.it/w0438defk5q61.jpg',
    thumbnail:
      'https://b.thumbs.redditmedia.com/EAO7VzZTTu249xtEdVo76JVrQL7iDIMSf0mY1QGEs6I.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617104510,
    upvotes: 1654,
    upvoteRatio: 0.93,
  },
  {
    id: 'mgkoj4',
    type: 'meme',
    title: 'Being a girl on reddit starterpack',
    postLink: 'https://redd.it/mgkoj4',
    image: 'https://i.redd.it/uy2gxlc657q61.png',
    thumbnail:
      'https://b.thumbs.redditmedia.com/teFInCoLTWt60QQJqcbBtNW7ZrTx1PqfjQRxbw54uZI.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617123740,
    upvotes: 310,
    upvoteRatio: 0.96,
  },
  {
    id: 'mgkdtj',
    type: 'meme',
    title: 'r/BlackPeopleTwitter starter pack:',
    postLink: 'https://redd.it/mgkdtj',
    image: 'https://i.redd.it/jn4jxo6937q61.jpg',
    thumbnail:
      'https://b.thumbs.redditmedia.com/_UqjVqBKqNXqfFNxYlLv_pmUIf9dsyBkMMKSBV_Vnfs.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617122944,
    upvotes: 108,
    upvoteRatio: 0.76,
  },
  {
    id: 'mgdqjm',
    type: 'meme',
    title: 'Throwaway account starterpack',
    postLink: 'https://redd.it/mgdqjm',
    image: 'https://i.redd.it/pq3bmo19h5q61.png',
    thumbnail:
      'https://b.thumbs.redditmedia.com/bpkBfyOU8D3mbhC7LfR-K0Zfb-Zvx7-PuqUaVeIC8HY.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617103492,
    upvotes: 304,
    upvoteRatio: 1,
  },
  {
    id: 'mghi9s',
    type: 'meme',
    title: 'Recent Nickelodeon Sitcoms Starter Pack',
    postLink: 'https://redd.it/mghi9s',
    image: 'https://i.redd.it/12dol36xf6q61.jpg',
    thumbnail:
      'https://b.thumbs.redditmedia.com/tyPtJiVF1BQdc7D46vl6-pKEhCm-mCqYh_fCWCxGKfY.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617115117,
    upvotes: 203,
    upvoteRatio: 0.98,
  },
  {
    id: 'mgqjq1',
    type: 'meme',
    title: 'The Boomer-Owned Business Starter Pack',
    postLink: 'https://redd.it/mgqjq1',
    image: 'https://i.redd.it/2t0rr8pkh8q61.jpg',
    thumbnail:
      'https://b.thumbs.redditmedia.com/Osu5p7g2ib8dHbvbxy2Kli4FrrCnXchJnRvYKUvjYQY.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617139885,
    upvotes: 27,
    upvoteRatio: 0.97,
  },
  {
    id: 'mgjjo5',
    type: 'meme',
    title: '"I sell crafts on Etsy and I designed my own logo" Starter Pack',
    postLink: 'https://redd.it/mgjjo5',
    image: 'https://i.redd.it/qmpusnwgw6q61.jpg',
    thumbnail:
      'https://b.thumbs.redditmedia.com/V4XUkYvAqZeUKB5M04wXVrK2jQZ_LseaKhg0G5ZoADg.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617120679,
    upvotes: 123,
    upvoteRatio: 0.98,
  },
  {
    id: 'mgn9rk',
    type: 'meme',
    title: 'Arab parent starter pack',
    postLink: 'https://redd.it/mgn9rk',
    image: 'https://i.redd.it/62ia8xrkq7q61.jpg',
    thumbnail:
      'https://b.thumbs.redditmedia.com/MXieAQOZ_O6izKvJG6dXm5WVujJfd-eyD1CH4jjQcnc.jpg',
    subreddit: 'starterpacks',
    NSFW: false,
    spoiler: false,
    createdUtc: 1617130788,
    upvotes: 73,
    upvoteRatio: 0.96,
  },
];

module.exports = {
  dummyPost,
  dummyPack,
};
